# Screen Settings
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_COLOR = "black"

# Game Settings
TICK_DELAY = 60

# Asteroid Settings
ASTEROID_COLOR = "white"
ASTEROID_KINDS = 3
ASTEROID_LINE_WIDTH = 2
ASTEROID_MIN_RADIUS = 20
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPAWN_RATE = 0.8  # seconds

# Player Settings
PLAYER_COLOR = "white"
PLAYER_LINE_WIDTH = 2
PLAYER_RADIUS = 20
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300