# Screen Settings
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_COLOR = "black"

# Game Settings
TICK_DELAY = 60

# Asteroid Settings
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Player Settings
PLAYER_RADIUS = 20
PLAYER_COLOR = "white"
PLAYER_LINE_WIDTH = 2