# Screen Settings
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_COLOR = "black"

# Game Settings
TICK_DELAY = 60
GAME_OVER_TEXT = "Game over!"

# Asteroid Settings
ASTEROID_COLOR = "white"
ASTEROID_KINDS = 3
ASTEROID_LINE_WIDTH = 2
ASTEROID_MIN_RADIUS = 20
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MIN_DESTROYED_ANGLE = 20
ASTEROID_MAX_DESTROYED_ANGLE = 50
ASTEROID_MIN_SPLIT = 2
ASTEROID_MAX_SPLIT = 2
ASTEROID_ACCELERATION = 1.2

# Player Settings
PLAYER_COLOR = "white"
PLAYER_LINE_WIDTH = 2
PLAYER_RADIUS = 20
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_SHOOT_SPEED = 500
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300

# Shot Settings
SHOT_COLOR = "white"
SHOT_LINE_WIDTH = 2
SHOT_RADIUS = 5